### ISSUE TITLE
spacy 3.1.1 doc.ents type change

### ISSUE THREAD

**Issue by mirandachong** [LeapBeyond/scrubadub#122]
New version of spacy seems to be causing `_get_affix_and_spacy_entities` in`spacy_name_title.py` to fail - at line 165 (doc.ents + doc._.person_titles) which is currently resulting in TypeError: can only concatenate tuple (not "list") to tuple.
Investigate if doc.ents type has changed

**Comment by thomasbird** [comment]
Fixed in MR #124
