### ISSUE TITLE
Examples for adding a new type of filth detector does not work.

### ISSUE THREAD

**Issue by gpetepg** [LeapBeyond/scrubadub#125]
The example here doesn't seem to work. https://scrubadub.readthedocs.io/en/latest/usage.html#adding-a-new-type-of-filth-detector

I am using python 3.9.5 in a Jupyter notebook.

<img width="1115" alt="Screen Shot 2021-09-16 at 5 39 56 PM" src="https://user-images.githubusercontent.com/24799706/133706060-d5921ca5-db3b-4211-8b79-ffbd29efee36.png">

**Comment by thomasbird** [comment]
Yep you're right, thanks for the report. A working example will include 
```filth_cls = MyFilth```
just under line 7 (`name = ...`).

Hopefully that'll work for you.

**Comment by gpetepg** [comment]
Thanks Thomas.
