### ISSUE TITLE
Examples in localization.rst do not work as intended.

### ISSUE THREAD

**Issue by gpetepg** [LeapBeyond/scrubadub#127]
Running Python3.8 on a Jupyter notebook.

<img width="1096" alt="Screen Shot 2021-09-21 at 7 01 47 PM" src="https://user-images.githubusercontent.com/24799706/134271898-cbc43ef2-19ac-485a-9734-7b3eada60874.png">

**Comment by thomasbird** [comment]
Looks like you were looking at the pre-release version of the documentation, because until today that feature hadn't been released. However the good news is that from today it should work!
