### ISSUE TITLE
Connecting Scrubadub to common PII API

### ISSUE THREAD

**Issue by ontocord** [LeapBeyond/scrubadub#137]
@thomasbird ! This is a great library. I wanted to see if you all would be interested in working with a common Privacy API standards that a few industry and privacy policy folks are working on: https://docs.google.com/document/d/1WEVx3QAnoIoPSUf66HYf7tCuT_KMWXdm4pU4N9JUz9I/edit#

I thought your documentation and framework, esp for localization was really good: https://github.com/LeapBeyond/scrubadub/blob/master/docs/localization.rst

We just created our github repo to put the API specs into it, and then create connectors to specific Privacy libraries here https://github.com/piisa.

Hope to hear from the Scrubadub team!

**Comment by thomasbird** [comment]
Sadly i will not be able to contribute due to other commitments, but best of luck, it sounds like an interesting idea!
