### ISSUE TITLE
Scrubadub is not treating JSON as String

### ISSUE THREAD

**Issue by ian-lewis-d** [LeapBeyond/scrubadub#138]
I am using scrubadub to clean email addresses in a number of fields. Some of the fields are JSON strings.

Short fields are handled without any issues but long JSON data is split into rows, which are then not reassembled. 

**Example**

**Post Scrubbing**

```
Name: payment_data, dtype: object"|"[{""name"":""Servicing"",""quantity"":1,""price"":100000}]"|100000|0|NO-DEPOSIT||0|0|||"0    {""amount"":100000,""deposit_amount"":0,""plan"":{""a...
1    {""amount"":60000,""plan"":{""agreement_duration_mo...
2    {""amount"":100100,""deposit_amount"":0,""plan"":{""a...
3    {""amount"":100000,""deposit_amount"":0,""plan"":{""a...
4    {""amount"":100000,""deposit_amount"":0,""plan"":{""a...
5    {""amount"":100000,""deposit_amount"":0,""plan"":{""a...
6    {""amount"":100000,""deposit_amount"":0,""plan"":{""a...
7    {""amount"":100100,""deposit_amount"":0,""plan"":{""a...
8    {""amount"":1000,""deposit_amount"":0,""plan"":{""agr...
9    {""amount"":100000,""deposit_amount"":0,""plan"":{""a...
```

This is the output to CSV, oe Parquet. I have tried simply using Pandas to_csv without the scrubbing and that works as expected.

Do you have any suggestions for how I can disable the seemingly automatic JSON detection and treat the data as a string.

EDIT: I can see now that the list is in the form of a <class 'pandas.core.series.Series'>

**Comment by thomasbird** [comment]
Scrubadub is not designed to handle anything other than plain text and so this use case it's not supported. I would suggest you load your data with pandas and loop over all rows/columns passing the individual strings to scrubadub rather than the whole CSV. Good luck!
