### ISSUE TITLE
Address installation lists lookalike dependency

### ISSUE THREAD

**Issue by hilaryp** [LeapBeyond/scrubadub#140]
Hi! It looks like the [address installation instructions](https://github.com/LeapBeyond/scrubadub/blob/master/docs/addresses.rst#installation) list the wrong postal package. `pypostal` points to [this archived project](https://github.com/hudora/pyPostal) on PyPi, when I think what's wanted is `pip install postal` for [this project](https://github.com/openvenues/pypostal).

Happy to submit a PR, but probably faster for someone who already has the project forked to fix. :)

**Comment by thomasbird** [comment]
I'll release this fix with the next version, thanks for spotting this!
