### ISSUE TITLE
Questions regarding the conflict results in different detectors

### ISSUE THREAD

**Issue by chocolocked** [LeapBeyond/scrubadub#141]
just wondering how does the scrubber handle conflicts of information produced by different detectors.
For example, stanfordentitydetector might produce something like {{LOC}}, while the address might labeled the same text as {{ADDRESS}}, when i have both detectors added to my scrubber, how does it solve the issue? 
Does it depends on the order of the detector added or something else? thanks :)

**Comment by thomasbird** [comment]
In that case the detected pieces of `Filth` are combined into a `MergedFilth`. If you're using the python API you can access the `merged_filth.filths` attribute and see the individual pieces of filth. If you're just looking at the textual output it would appear as (in your example) {{LOC+ADDRESS}}. Hope this helps.
