### ISSUE TITLE
Replace with nothing

### ISSUE THREAD

**Issue by mattare2** [LeapBeyond/scrubadub#33]
Is there an easy way to omit the placeholders, and simply replace with nothing?  (Aside from regex removing things in {{}})

**Comment by deanmalmgren** [comment]
http://scrubadub.readthedocs.io/en/stable/advanced_usage.html#customizing-filth-markers

**Comment by deanmalmgren** [comment]
Hey @mattare2, sorry... right after I closed this out I realized what you were asking. 

It sounds like you additionally want to get rid of the `EMAIL` or `NAME` parts as well as the `{{` and `}}`. When scrubadub was developed, it was created from the point-of-view that omitting the context of an omitted field was "bad form", but I can see why you'd want to do this. 

I can imagine accomplishing this with a few options that have to do with overriding the behavior in [`scrubadub.filths.base.Filth`](https://github.com/datascopeanalytics/scrubadub/blob/master/scrubadub/filth/base.py):

1. overriding the `Filth.placeholder` property to return an empty string while simultaneously setting the `Filth.prefix` and `Filth.suffix` to an empty string, as I preemptively suggested with the documentation link above.

2. overriding the `Filth.replace_with` method to return an empty string. 

3. creating a new `replace_with='nothing'` keyword argument for `Filth.replace_with` that has the desired behavior.

Here's an example of doing this with option 2 that doesn't involve changing the scrubadub source code directly:

```python
import scrubadub.filth.base

def replace_with(*args, **kwargs):
    return ''
scrubadub.filth.base.Filth.replace_with = replace_with

import scrubadub
print scrubadub.clean(text)
```

Please note that this won't work for any `Filth` that overrides the `Filth.replace_with` method, like `CredentialFilth`.

If you think this is a common enough use case, it would be nice to include something like option 3 as a PR, which I'd certainly welcome!

**Comment by thomasbird** [comment]
The latest version of scrubadub supports this now:

```
import scrubadub
scrubber = scrubadub.Scrubber(post_processor_list=[
    scrubadub.post_processors.FilthRemover(),
])
scrubber.clean("Contact me at 522-368-8530 or hernandezjenna@example.com")
'Contact me at  or '
```
