### ISSUE TITLE
remove_detector/add_detector not working

### ISSUE THREAD

**Issue by JoshiHarshit** [LeapBeyond/scrubadub#45]
![Capture](https://user-images.githubusercontent.com/22893082/74844232-2c5e7400-5353-11ea-81f3-85c2f39f43ba.PNG)
Facing a issue I am unable to add or remove detector.

**Comment by thomasbird** [comment]
Hi @JoshiHarshit, 

If you use the `scrubber` instance (that you just configured) to clean the data instead of the global package (with the default configuration), you should be sorted.

```python
>>> import scrubadub
>>> scrubber = scrubadub.Scrubber()
>>> scrubber.clean('email@example.com')
'{{EMAIL}}'
>>> scrubber.remove_detector('email')
>>> scrubber.clean('email@example.com')
'email@example.com'
```

Let us know if you have any further issues!
