### ISSUE TITLE
Create evaluation dataset

### ISSUE THREAD

**Issue by thomasbird** [LeapBeyond/scrubadub#59]
It would be good to understand how well scrubadub performs. To do this we could use open datasets or generated datasets to evaluate the performance of scrubadub. Fake data coule be generated with a package such as faker.

**Comment by aCampello** [comment]
+1 For this. 

I would like to see/implement, in particular for names, how the detector works for non-British non-American names. This is probably doable with synthetic/faker data.

**Comment by thomasbird** [comment]
I've actually started on this a little...

You can now make fake documents here:
https://github.com/LeapBeyond/scrubadub/blob/master/scrubadub/comparison.py#L191

Then there is a script in the CI now that evaluates the performance here:
https://github.com/LeapBeyond/scrubadub/blob/master/tests/benchmark_accuracy.py

And those numbers are filling in this new page:
https://scrubadub.readthedocs.io/en/latest/accuracy.html

**Comment by thomasbird** [comment]
Accuracy is now printed in the CI/CD. This is also displayed on the new accuracy page. As a follow on task #72 has been created to do this on real data.
