### ISSUE TITLE
Resolve current py35 issues

### ISSUE THREAD

**Issue by thomasbird** [LeapBeyond/scrubadub#67]
Build for py35 is failing, fix or drop support for py35.

**Comment by aCampello** [comment]
Since 3.5 has reached end of life, maybe we can just upgrade to 3.6: https://www.python.org/downloads/release/python-350/

**Comment by thomasbird** [comment]
Very true! One concern I have is that it's still the default python on ubuntu 18.04 LTS, which seems to be kinda popular in the corp world, so I'm hesitant to drop right away. Plus, I think it's working well in #68, such that we only need py36 for this particular detector.
